<?php

/**
 * @file
 * Contains pluginlearning.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function pluginlearning_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the pluginlearning module.
    case 'help.page.pluginlearning':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('implementation of field type, field widget, field formatter') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function pluginlearning_theme() {
  return [
    'pluginlearning' => [
      'render element' => 'children',
    ],
  ];
}
