<?php 

function alter1_form_FORM_ID_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
	dpm('fff');
  // Modification for the form with the given form ID goes here. For example, if
  // FORM_ID is "user_register_form" this code would run only on the user
  // registration form.
  // Add a checkbox to registration form about agreeing to terms of use.

}

function alter1_form_alter(&$form, \Drupal\Core\Form\FormStateInterface &$form_state, $form_id) {
    dpm($form_id);//get the form_id
    #dpm($form);//get the form
    }
